# Generated by Django 2.2.28 on 2026-03-06 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qsd', '0004_clean_class_qsds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasistaticdata',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='last edited'),
        ),
    ]
