# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsd', '0004_clean_class_qsds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasistaticdata',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quasistaticdata',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
    ]
