# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-07 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0002_auto_20151004_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerequest',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
