# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-19 20:56
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0004_auto_20210526_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainredirect',
            name='destination',
            field=models.CharField(help_text='A comma-seperated list of one or more real email address(es) that will receive the redirected email(s)', max_length=512),
        ),
        migrations.AlterField(
            model_name='plainredirect',
            name='original',
            field=models.CharField(help_text='A real or custom email address name (e.g., "directors" or "splash"). Any emails to &lt;original&gt;@&lt;yourdomain&gt; will be redirected to the destination email address(es).', max_length=512),
        ),
    ]
