# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 14:11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0005_auto_20220719_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='MessageVar',
            old_name='pickled_provider',
            new_name='pickled_provider_migration2024',
        ),
        migrations.AddField(
            model_name='MessageVar',
            name='pickled_provider',
            field=models.BinaryField(null=True),
        ),
    ]
