# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0005_auto_20220719_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevars',
            name='pickled_provider',
            field=models.BinaryField(),
        ),
    ]
