# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 21:31
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0006_textofemail_user'),
        ('dbmail', '0007_repickle_specialheaders'),
    ]

    operations = [
    ]
