# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 23:41
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0008_merge_20240509_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagevars',
            name='pickled_provider_migration2024',
        ),
        migrations.AlterField(
            model_name='messagevars',
            name='pickled_provider',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
