# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import math

def fill_requests(apps, schema_editor):
    TextOfEmail = apps.get_model('dbmail', 'TextOfEmail')
    MessageRequest = apps.get_model('dbmail', 'MessageRequest')
    requests = MessageRequest.objects.all()
    for req in requests:
        toes = TextOfEmail.objects.filter(created_at=req.created_at,
                                          subject = req.subject,
                                          send_from = req.sender)
        toes.update(messagerequest=req, msgtext="")

class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0009_auto_20240509_2341'),
    ]

    operations = [
        # need to add the field with null=True
        migrations.AddField(
            model_name='textofemail',
            name='messagerequest',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='dbmail.MessageRequest'),
        ),
        # fill in the message request for all texts
        migrations.RunPython(fill_requests, migrations.RunPython.noop),
        # now we can make null=False (requiring the field)
        migrations.AlterField(
            model_name='textofemail',
            name='messagerequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmail.MessageRequest'),
        ),
    ]
