# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import math

def fill_requests(apps, schema_editor):
    TextOfEmail = apps.get_model('dbmail', 'TextOfEmail')
    MessageRequest = apps.get_model('dbmail', 'MessageRequest')
    toe_table = TextOfEmail._meta.db_table
    mr_table = MessageRequest._meta.db_table
    schema_editor.execute(
        """
        UPDATE {toe} AS toe
        SET messagerequest_id = mr.id, msgtext = ''
        FROM {mr} AS mr
        WHERE toe.created_at = mr.created_at
          AND toe.subject = mr.subject
          AND toe.send_from = mr.sender
        """.format(toe=toe_table, mr=mr_table)
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0009_auto_20240509_2341'),
    ]

    operations = [
        # need to add the field with null=True
        migrations.AddField(
            model_name='textofemail',
            name='messagerequest',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='dbmail.MessageRequest'),
        ),
        # fill in the message request for all texts
        # MIT: many historical rows have no matching MessageRequest; field stays nullable
        migrations.RunPython(fill_requests, migrations.RunPython.noop),
    ]
