# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0010_textofemail_messagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='from_email',
            field=models.CharField(blank=True, default='', help_text='If specified, the FROM header will be overwritten with this email.', max_length=512),
        ),
        migrations.AlterField(
            model_name='emaillist',
            name='subject_prefix',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='messagerequest',
            name='msgtext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagerequest',
            name='sender',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagerequest',
            name='special_headers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messagerequest',
            name='subject',
            field=models.TextField(blank=True, default=''),
        ),
    ]
