# Generated by Django 2.2.28 on 2026-02-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0010_textofemail_messagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerequest',
            name='processed_by',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='messagerequest',
            name='sendto_fn_name',
            field=models.CharField(blank=True, choices=[('', 'send to user'), ('send_to_guardian', 'send to guardian'), ('send_to_emergency', 'send to emergency contact'), ('send_to_self_and_guardian', 'send to user and guardian'), ('send_to_self_and_emergency', 'send to user and emergency contact'), ('send_to_guardian_and_emergency', 'send to guardian and emergency contact'), ('send_to_self_and_guardian_and_emergency', 'send to user and guardian and emergency contact')], default='', help_text='The function that specifies, for each recipient of the message, which set of associated email addresses should receive the message.', max_length=128, verbose_name='sendto function'),
        ),
    ]
