# Generated by Django 2.2.28 on 2026-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0010_textofemail_messagerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainredirect',
            name='destination',
            field=models.CharField(help_text='A comma-separated list of one or more real email address(es) that will receive the redirected email(s)', max_length=512),
        ),
    ]
