# Generated by Django 2.2.28 on 2026-02-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20260106_2204'),
        ('dbmail', '0010_textofemail_messagerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=998, unique=True)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=998)),
                ('references', models.TextField(blank=True, default='')),
                ('sender', models.CharField(max_length=512)),
                ('sender_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient', models.CharField(max_length=512)),
                ('subject', models.CharField(max_length=998)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('raw_headers', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_outbound_reply', models.BooleanField(default=False)),
                ('replied_by', esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_replies', to='users.ESPUser')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmailThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=998)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('assigned_to', esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_threads', to='users.ESPUser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='inbox_attachments/%Y/%m/')),
                ('size', models.PositiveIntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dbmail.InboundEmail')),
            ],
        ),
        migrations.AddField(
            model_name='inboundemail',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='dbmail.InboundEmailThread'),
        ),
        migrations.CreateModel(
            name='InboundEmailReadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='dbmail.InboundEmailThread')),
                ('user', esp.db.fields.AjaxForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_read_statuses', to='users.ESPUser')),
            ],
            options={
                'unique_together': {('user', 'thread')},
            },
        ),
    ]
