# Generated by Django 2.2.28 on 2026-03-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_passwordrecoveryticket'),
        ('dbmail', '0011_populate_default_emaillists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainredirect',
            name='destination',
            field=models.CharField(help_text='A comma-separated list of one or more real email address(es) that will receive the redirected email(s)', max_length=512),
        ),
        migrations.CreateModel(
            name='HeldEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_part', models.CharField(help_text="The local part of the address (e.g. 'M100-students').", max_length=512)),
                ('raw_message', models.BinaryField(help_text='Raw RFC 2822 email message bytes (preserves MIME structure and attachments).')),
                ('recipients_json', models.TextField(help_text='JSON-serialized list of recipient email addresses.')),
                ('handler_class', models.CharField(help_text="Handler class name (e.g. 'ClassList', 'SectionList').", max_length=128)),
                ('subject_prefix', models.CharField(blank=True, default='', max_length=64)),
                ('from_email_override', models.CharField(blank=True, default='', max_length=512)),
                ('cc_all', models.BooleanField(default=False)),
                ('preserve_headers', models.BooleanField(default=False)),
                ('emailcode', models.CharField(blank=True, default='', help_text='The emailcode from the handler (e.g. class code for subject prefix).', max_length=128)),
                ('sender', models.CharField(blank=True, default='', help_text='Original From header value.', max_length=512)),
                ('subject', models.CharField(blank=True, default='', help_text='Original Subject header value.', max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Optional reason for rejection.')),
                ('email_list', models.ForeignKey(blank=True, help_text='The EmailList rule that held this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmail.EmailList')),
                ('moderated_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected this email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_emails', to='users.ESPUser')),
            ],
            options={
                'verbose_name': 'Held email',
                'verbose_name_plural': 'Held emails',
                'ordering': ['-held_at'],
            },
        ),
    ]
