# Generated by Django 2.2.28 on 2026-03-06 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0011_populate_default_emaillists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The time this object was created at. Useful for informational purposes, and also as a safety mechanism for preventing un-sent (because of previous bugs and failures), out-of-date messages from being sent.'),
        ),
        migrations.AlterField(
            model_name='plainredirect',
            name='destination',
            field=models.CharField(help_text='A comma-separated list of one or more real email address(es) that will receive the redirected email(s)', max_length=512),
        ),
    ]
