# Generated by Django 2.2.28 on 2026-03-06 11:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0011_populate_default_emaillists'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagevars',
            name='provider_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagevars',
            name='pickled_provider',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plainredirect',
            name='destination',
            field=models.CharField(help_text='A comma-separated list of one or more real email address(es) that will receive the redirected email(s)', max_length=512),
        ),
    ]
