# Generated by Django 2.2.28 on 2026-02-23 09:43

from django.db import migrations, models
import django.db.models.deletion
import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20260106_2204'),
        ('dbmail', '0011_inbound_email_inbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InboxCannedResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seq', models.SmallIntegerField(default=0)),
                ('created_by', esp.db.fields.AjaxForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ESPUser')),
            ],
            options={
                'ordering': ['seq', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmailNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', esp.db.fields.AjaxForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_notes_created', to='users.ESPUser')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dbmail.InboundEmailThread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmailThreadLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', esp.db.fields.AjaxForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ESPUser')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeled_threads', to='dbmail.InboxLabel')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_labels', to='dbmail.InboundEmailThread')),
            ],
            options={
                'unique_together': {('thread', 'label')},
            },
        ),
    ]
