# Generated by Django 2.2.28 on 2026-02-23 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0012_inbox_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxlabel',
            name='color',
            field=models.CharField(help_text='Hex color code, e.g. #ff0000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit hex color (e.g. #ff0000).', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
