# Generated by Django 2.2.28 on 2026-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0012_auto_20260306_0001'),
        ('dbmail', '0012_auto_20260224_0619'),
    ]

    operations = [
    ]
