# Generated by Django 4.2.30 on 2026-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0013_auto_20260325_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBounceRecord',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bounce_count', models.IntegerField(default=1)),
                ('last_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('status_code', models.CharField(
                    blank=True,
                    max_length=10,
                    null=True
                )),
                ('reason', models.TextField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
