# Generated by Django 2.2.28 on 2026-04-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0012_auto_20260319_1454'),
        ('dbmail', '0013_auto_20260325_1833'),
    ]

    operations = [
    ]
