# Generated by Django 2.2.28 on 2026-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmail', '0013_auto_20260325_1833'),
        ('dbmail', '0013_merge_20260316_1338'),
    ]

    operations = [
    ]
