# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-02-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
