# Generated by Django 2.2.28 on 2026-02-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_teacher_type',
            field=models.BooleanField(default=False),
        ),
    ]
