# Generated by Django 2.2.28 on 2026-02-22

from django.db import migrations


def backfill_is_teacher_type(apps, schema_editor):
    EventType = apps.get_model("cal", "EventType")

    EventType.objects.filter(
        description__in=["Teacher Interview", "Teacher Training"]
    ).update(is_teacher_type=True)


def reverse_backfill(apps, schema_editor):
    EventType = apps.get_model("cal", "EventType")

    EventType.objects.filter(
        description__in=["Teacher Interview", "Teacher Training"]
    ).update(is_teacher_type=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_eventtype_is_teacher_type'),
    ]

    operations = [
        migrations.RunPython(backfill_is_teacher_type, reverse_backfill),
    ]