# Generated by Django 5.2.16 on 2026-09-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_backfill_is_teacher_type'),
        ('program', '0043_alter_phasezerorecord_program'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('program', 'start', 'end'), name='unique_event_program_start_end'),
        ),
    ]
