# Generated by Django 5.2.16 on 2026-09-16 05:59

from django.db import migrations
from django.db.models import Count


def dedupe_events(apps, schema_editor):
    Event = apps.get_model('cal', 'Event')
    UserAvailability = apps.get_model('users', 'UserAvailability')
    ScheduleTestTimeblock = apps.get_model('program', 'ScheduleTestTimeblock')
    ScheduleTestOccupied = apps.get_model('program', 'ScheduleTestOccupied')
    ScheduleTestCategory = apps.get_model('program', 'ScheduleTestCategory')
    ScheduleTestSectionList = apps.get_model('program', 'ScheduleTestSectionList')
    VolunteerRequest = apps.get_model('program', 'VolunteerRequest')
    ClassSection = apps.get_model('program', 'ClassSection')
    ClassSubject = apps.get_model('program', 'ClassSubject')
    Resource = apps.get_model('resources', 'Resource')

    dupes = (
        Event.objects.values('program', 'start', 'end', 'event_type')
        .annotate(cnt=Count('id'))
        .filter(cnt__gt=1)
    )

    for group in dupes:
        rows = Event.objects.filter(
            program=group['program'], start=group['start'],
            end=group['end'], event_type=group['event_type'],
        ).order_by('id')
        keeper = rows.first()
        losers = list(rows.exclude(id=keeper.id))
        loser_ids = [l.id for l in losers]

        UserAvailability.objects.filter(event_id__in=loser_ids).update(event_id=keeper.id)
        ScheduleTestTimeblock.objects.filter(timeblock_id__in=loser_ids).update(timeblock_id=keeper.id)
        ScheduleTestOccupied.objects.filter(timeblock_id__in=loser_ids).update(timeblock_id=keeper.id)
        ScheduleTestCategory.objects.filter(timeblock_id__in=loser_ids).update(timeblock_id=keeper.id)
        ScheduleTestSectionList.objects.filter(timeblock_id__in=loser_ids).update(timeblock_id=keeper.id)
        VolunteerRequest.objects.filter(timeslot_id__in=loser_ids).update(timeslot_id=keeper.id)
        Resource.objects.filter(event_id__in=loser_ids).update(event_id=keeper.id)

        for section in ClassSection.objects.filter(meeting_times__id__in=loser_ids):
            section.meeting_times.add(keeper)
            for lid in loser_ids:
                section.meeting_times.remove(lid)
        for subject in ClassSubject.objects.filter(meeting_times__id__in=loser_ids):
            subject.meeting_times.add(keeper)
            for lid in loser_ids:
                subject.meeting_times.remove(lid)

        Event.objects.filter(id__in=loser_ids).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_backfill_is_teacher_type'),
        ('program', '0026_auto_20221122_2100'),
        ('resources', '0009_resourcetype_cascade'),
    ]

    operations = [
        migrations.RunPython(dedupe_events, noop_reverse),
    ]
