# Generated by Django 5.2.16 on 2026-09-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_dedupe_events_before_constraint'),
        ('program', '0045_backfill_studentappreview_class_subject'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(
                fields=('program', 'start', 'end', 'event_type'),
                name='unique_event_program_start_end',
            ),
        ),
    ]
