# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-26 19:21
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarcategory',
            options={'verbose_name_plural': 'Nav bar categories'},
        ),
        migrations.AlterModelOptions(
            name='navbarentry',
            options={'verbose_name_plural': 'Nav bar entries'},
        ),
    ]
