# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210526_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarentry',
            name='link',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
