# Generated by Django 2.2.28 on 2026-03-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20260327_1225'),
        ('web', '0003_migrate_file_extensions_to_lowercase'),
    ]

    operations = [
    ]
