#!/bin/bash
set -euf -o pipefail

if [ "$TRAVIS_JOB" = "test" ]; then
    cp esp/esp/local_settings.py.travis esp/esp/local_settings.py
    ln -s `pwd`/esp/public/media/default_images esp/public/media/images
    ln -s `pwd`/esp/public/media/default_styles esp/public/media/styles
    # the postgres service in Github Actions sets up the database for us
    if [ "$GITHUB_ACTIONS" != true ]; then
        psql -c "CREATE ROLE testuser PASSWORD 'testpassword' LOGIN CREATEDB;" -U postgres
        psql -c "CREATE DATABASE test_django OWNER testuser;" -U postgres
    fi
elif [ "$TRAVIS_JOB" = "lint" ]; then
    :
else
    echo "Unknown TRAVIS_JOB: $TRAVIS_JOB"
    exit 1
fi
