#!/bin/bash
set -euf -o pipefail

sudo apt-get update

# install pip
sudo add-apt-repository universe
sudo apt-get install -y curl
curl https://bootstrap.pypa.io/2.7/get-pip.py --output get-pip.py
sudo python2 get-pip.py
