#!/bin/bash
set -euf -o pipefail

if [ "$TRAVIS_JOB" = "test" ]; then
    cd esp
    ./manage.py collectstatic --noinput -v 0
    ./manage.py test
elif [ "$TRAVIS_JOB" = "lint" ]; then
    deploy/lint
else
    echo "Unknown TRAVIS_JOB: $TRAVIS_JOB"
    exit 1
fi
