# Generated by Django 2.2.28 on 2026-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customforms', '0002_auto_20151109_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
