# Generated by Django 5.2.15 on 2026-08-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customforms', '0003_auto_20260306_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['seq']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['seq']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['seq']},
        ),
    ]
