# Generated by Django 2.2.28 on 2026-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customforms', '0003_auto_20260306_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
