#!/bin/sh
### BEGIN INIT INFO
# Provides:          esp
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the esp django interface.
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=django-esp
DAEMON=/esp/esp/webserver_settings/$NAME.sh
DESC="$NAME fastcgi server"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

DAEMON_OPTS="pidfile=$PIDFILE"

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" $NAME
	$DAEMON $DAEMON_OPTS
        echo
    ;;
  stop)
	log_daemon_msg "Stopping $DESC" $NAME
        if [ -e $PIDFILE ]; then
           kill `cat $PIDFILE`
           rm -f $PIDFILE
        fi
        echo
    ;;
  
  restart|force-reload)
	$0 stop
        sleep 1s
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	exit 1
	;;
esac

exit 0
