# Generated by Django 2.2.28 on 2026-01-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qsdmedia', '0002_auto_20151126_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='owner_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['classsubject', 'program']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
