# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsdmedia', '0003_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_extension',
            field=models.TextField(blank=True, default='', editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_name',
            field=models.TextField(blank=True, default='', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='format',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='media',
            name='hashed_name',
            field=models.TextField(blank=True, default='', editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='mime_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=256),
        ),
    ]
