name: Discussion
description: Start a discussion or ask a question
title: "[Discussion]: "
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Want to discuss something about the project? Ask a question or start a conversation here!

  - type: textarea
    id: topic
    attributes:
      label: Topic
      description: What would you like to discuss?
      placeholder: Describe the topic of discussion...
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Provide more details or context for the discussion.
      placeholder: Share your thoughts, questions, or ideas...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Link any related issues, PRs, or external resources.
    validations:
      required: false
