#!/bin/bash
set -euf -o pipefail

if [ "$CI_JOB" = "test" ]; then
    cd esp
    ./manage.py collectstatic --noinput -v 0
    coverage run --source=. ./manage.py test
    coverage xml
elif [ "$CI_JOB" = "lint" ]; then
    deploy/lint
else
    echo "Unknown CI_JOB: $CI_JOB"
    exit 1
fi
