# catch requests not going to our hostname and return a 444 error:
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 444;
}
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
    return 444;
}

# serve the actual website:
server {
    server_name esp.mit.edu;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/esp.mit.edu/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/esp.mit.edu/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location = /favicon.ico {
        return 301 /media/images/favicon.ico;
    }

    location = /robots.txt {
        return 301 /media/robots.txt;
    }

    location = /googledd764b513e81a270.html { # required for google search console
        alias /esp/esp/public/media/googledd764b513e81a270.html;
    }

    # Django media
    location /media {
        rewrite ^/media/uploaded/([^/]*)/([^/]*)$ /download/$2;
        alias /esp/esp/public/media;
    }

    location /static {
        alias /esp/esp/public/static;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 15m;
    }

    # larger upload size
    client_max_body_size 20M;

    # wiki redirect; esp.mit.edu/wiki was the pre-2016 URL
    rewrite ^/wiki$ https://esp-wiki.mit.edu;
    rewrite ^/wiki/(.*)$ https://esp-wiki.mit.edu/$1;

    # mailman redirect; esp.mit.edu/cgi-bin/mailman was the pre-2016 URL
    rewrite ^/cgi-bin/mailman/(.*)$ http://esp-mail.mit.edu/$1;

    # piwik redirect; esp.mit.edu/piwik was the pre-2016 URL
    rewrite ^/piwik$ https://esp-piwik.mit.edu;
    rewrite ^/piwik/(.*)$ https://esp-piwik.mit.edu/$1;
}
server {
    if ($host = esp.mit.edu) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name esp.mit.edu;

    listen 80;
    return 404; # managed by Certbot
}
