#!/bin/bash -e

# http://stackoverflow.com/a/4774063
pushd "$(dirname "$0")" > /dev/null
SCRIPTDIR="$(pwd -P)"
popd > /dev/null

BASEDIR="$(dirname "$SCRIPTDIR")"

echo "Running lint checks..."

# Lint configuration is in .flake8 at the repository root.
# See that file for the list of enabled/ignored checks and excluded paths.
flake8 "$BASEDIR"

# Those escape codes the cursor up a line and forward 22 columns (past
# "Running lint checks...").  We can't just `echo -n` above, because if there
# is lint output we want it on its own line(s).  We only get here if there are
# no errors.
echo -e "\033[1A\033[22C success!"
