# Generated by Django 2.2.28 on 2026-03-02 02:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToolbarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500, validators=[django.core.validators.URLValidator()])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin Toolbar Link',
                'verbose_name_plural': 'Admin Toolbar Links',
                'ordering': ['order', 'title'],
            },
        ),
    ]
