# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-28 15:17
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200531_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradechangerequest',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='gradechangerequest',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
