# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 20:04
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations

def set_my_defaults(apps, schema_editor):
    ContactInfo = apps.get_model('users', 'ContactInfo')
    RegistrationProfile = apps.get_model('program', 'RegistrationProfile')

    # Pre-fetch the latest RP user for each CI for each relationship type.
    # Returns {ci_id: user_id} mapping the latest (by last_ts) RP per CI.
    def latest_user_by_ci(field):
        result = {}
        for rp in RegistrationProfile.objects.filter(
            **{field + '__isnull': False}
        ).order_by('last_ts').values(field, 'user'):
            result[rp[field]] = rp['user']  # later (newer) entries overwrite earlier
        return result

    as_user_map      = latest_user_by_ci('contact_user')
    as_guardian_map  = latest_user_by_ci('contact_guardian')
    as_emergency_map = latest_user_by_ci('contact_emergency')

    # Build priority update mapping: user > guardian > emergency.
    updates = {}  # ci_id -> user_id
    for ci_id, user_id in as_user_map.items():
        updates[ci_id] = user_id
    for ci_id, user_id in as_guardian_map.items():
        if ci_id not in updates:
            updates[ci_id] = user_id

    # Emergency contacts need a name check before assigning; fetch only the
    # fields we need (id, first_name, last_name) rather than full instances.
    emergency_only_ids = set(as_emergency_map.keys()) - set(updates.keys())
    delete_emergency_ids = []
    if emergency_only_ids:
        for ci in ContactInfo.objects.filter(
            id__in=emergency_only_ids, user=None
        ).values('id', 'first_name', 'last_name'):
            if ci['first_name'] and ci['last_name']:
                updates[ci['id']] = as_emergency_map[ci['id']]
            else:
                # We want to delete emergency contact info for non-students
                delete_emergency_ids.append(ci['id'])

    # Bulk-update all assignments in one shot using psycopg2 execute_values
    # (assembles a single UPDATE ... FROM (VALUES ...) statement) rather than
    # one save() per row — the previous bottleneck at ~200k rows.
    if updates:
        from psycopg2.extras import execute_values
        table = ContactInfo._meta.db_table
        with schema_editor.connection.cursor() as cursor:
            execute_values(
                cursor,
                """
                UPDATE {table} AS ci
                SET user_id = data.user_id
                FROM (VALUES %s) AS data(ci_id, user_id)
                WHERE ci.id = data.ci_id AND ci.user_id IS NULL
                """.format(table=table),
                list(updates.items()),
                page_size=1000,
            )

    # Bulk delete emergency contacts without names: clear FK first so we don't
    # accidentally delete the RegistrationProfile when we delete the ContactInfo
    if delete_emergency_ids:
        RegistrationProfile.objects.filter(
            contact_emergency_id__in=delete_emergency_ids
        ).update(contact_emergency=None)
        ContactInfo.objects.filter(id__in=delete_emergency_ids).delete()

    # Delete all remaining user=None CIs (orphans not referenced by any RP).
    # After the bulk update above, only true orphans still have user_id IS NULL.
    ContactInfo.objects.filter(user=None).delete()

def reverse_func(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200828_1517'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_func),
    ]
