# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-04 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200828_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address_state',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name=b'State'),
        ),
    ]
