# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-08 20:04
from __future__ import unicode_literals

from django.db import migrations

def set_my_defaults(apps, schema_editor):
    ContactInfo = apps.get_model('users', 'ContactInfo')
    for ci in ContactInfo.objects.all():
        if ci.user is None:
            # Look for associated registration profiles with user info
            if ci.as_user.exists():
                ci.user = ci.as_user.latest('last_ts').user
                ci.save()
            elif ci.as_guardian.exists():
                ci.user = ci.as_guardian.latest('last_ts').user
                ci.save()
            elif ci.as_emergency.exists():
                if not (ci.first_name and ci.last_name):
                    # We want to delete emergency contact info for non-students
                    # First remove the emergency contact from the RegistrationProfile,
                    # so we don't accidentally delete the RegistrationProfile when we delete the ContactInfo
                    ci.as_emergency.update(contact_emergency = None)
                    ci.delete()
                else:
                    ci.user = ci.as_emergency.latest('last_ts').user
                    ci.save()
            else:
                # ContactInfo isn't associated with any registration profiles or user
                ci.delete()

def reverse_func(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200828_1517'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_func),
    ]
