# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-17 08:39
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models

def set_my_defaults(apps, schema_editor):
    Record = apps.get_model('users', 'Record')
    recs = Record.objects.filter(event="extra_form_done")
    if recs.exists():
        for rec in recs:
            # Guess whether it was for the teacher or student custom form
            if rec.user.groups.filter(name='Teacher').exists() and rec.program.program_modules.filter(handler='TeacherCustomFormModule').exists():
                rec.event = "teacher_extra_form_done"
            else:
                rec.event = "student_extra_form_done"
            rec.save()

def reverse_func(apps, schema_editor):
    Record = apps.get_model('users', 'Record')
    Record.objects.filter(event__contains="extra_form_done").update(event="extra_form_done")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210526_1921'),
        ('modules', '0029_auto_20210616_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='event',
            field=models.CharField(choices=[(b'student_survey', b'Completed student survey'), (b'teacher_survey', b'Completed teacher survey'), (b'reg_confirmed', b'Confirmed registration'), (b'attended', b'Attended program'), (b'checked_out', b'Checked out of program'), (b'conf_email', b'Was sent confirmation email'), (b'teacher_quiz_done', b'Completed teacher quiz'), (b'paid', b'Paid for program'), (b'med', b'Submitted medical form'), (b'med_bypass', b'Recieved medical bypass'), (b'liab', b'Submitted liability form'), (b'onsite', b'Registered for program onsite'), (b'schedule_printed', b'Printed student schedule onsite'), (b'teacheracknowledgement', b'Did teacher acknowledgement'), (b'studentacknowledgement', b'Did student acknowledgement'), (b'lunch_selected', b'Selected a lunch block'), (b'student_extra_form_done', b'Filled out Student Custom Form'), (b'teacher_extra_form_done', b'Filled out Teacher Custom Form'), (b'extra_costs_done', b'Filled out Student Extra Costs Form'), (b'donation_done', b'Filled out Donation Form'), (b'waitlist', b'Waitlisted for a program'), (b'interview', b'Teacher-interviewed for a program'), (b'teacher_training', b'Attended teacher-training for a program'), (b'teacher_checked_in', b'Teacher checked in for teaching on the day of the program'), (b'twophase_reg_done', b'Completed two-phase registration')], max_length=80),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
    ]
