# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-16 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_espuserdata'),
        ('users', '0025_auto_20210617_0839'),
    ]

    operations = [
    ]
