# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-26 20:28
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations

def link_event(apps, schema_editor):
    Record = apps.get_model('users', 'Record')
    RecordType = apps.get_model('users', 'RecordType')

    # Normalize legacy names before creating RecordTypes
    Record.objects.filter(event="medical").update(event="med")
    Record.objects.filter(event="liability").update(event="liab")

    # Collect unique non-empty event names
    event_names = set(
        Record.objects.exclude(event="").exclude(event__isnull=True)
        .values_list("event", flat=True)
    )

    # Ensure a RecordType exists for each name (small set, ~20 entries)
    for name in event_names:
        RecordType.objects.get_or_create(name=name, defaults={"description": name})

    # Bulk-link records by event name — one UPDATE per unique event name
    for rt in RecordType.objects.filter(name__in=event_names):
        Record.objects.filter(event=rt.name).update(event_link=rt)

def unlink_event(apps, schema_editor):
    Record = apps.get_model('users', 'Record')
    RecordType = apps.get_model('users', 'RecordType')
    for rt in RecordType.objects.all():
        Record.objects.filter(event_link=rt).update(event=rt.name)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_create_events'),
    ]

    operations = [
        migrations.RunPython(link_event, unlink_event),
    ]
