# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-26 21:28
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_transfer_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='event',
        ),
    ]
