# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 13:56
from __future__ import unicode_literals
from django.db import migrations, models
from esp.utils.cucumber import load_python2_pickle
import pickle


def repickle_q_filters(apps, schema_editor):
    PersistentQueryFilter = apps.get_model('users', 'PersistentQueryFilter')
    for pqf in PersistentQueryFilter.objects.all():
        q_filter = load_python2_pickle(pqf.q_filter)
        pqf.q_filter = pickle.dumps(q_filter) 
        pqf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20240306_0103'),
    ]

    operations = [
        migrations.RunPython(repickle_q_filters),
    ]
