# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20240306_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentqueryfilter',
            name='q_filter',
            field=models.BinaryField(),
        ),
    ]
