# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 13:56
from __future__ import unicode_literals
from django.db import migrations, models
from esp.utils.cucumber import load_python2_pickle
import pickle


def repickle_q_filters(apps, schema_editor):
    OldPersistentQueryFilter = apps.get_model('users', 'PersistentQueryFilter_old')
    PersistentQueryFilter = apps.get_model('users', 'PersistentQueryFilter')
    for opqf in PersistentQueryFilter.objects.all():
		q_filter = load_python2_pickle(pqf.q_filter)
        pqf = PersistentQueryFilter(opqf) # TODO: create with all fields except q_filter?
        pqf.q_filter = pickle.dumps(q_filter) 
        pqf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20240306_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persistentqueryfilter',
            old_name='q_filter',
            new_name='q_filter_old',
        ),
        migrations.AddField(
            model_name='persistentqueryfilter',
            name='q_filter',
            field=models.BinaryField(),
        ),
        migrations.RunPython(repickle_q_filters),
        migrations.RemoveField(
            model_name='persistentqueryfilter',
            name='q_filter_old',
        )
    ]
