# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_contactinfo_address_postal'),
        ('users', '0036_auto_20240309_1356'),
    ]

    operations = [
    ]
