# Generated by Django 2.2.28 on 2026-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_migrate_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='studentrep',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
