# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_merge_20260426'),
    ]

    operations = [
        # AlterField operations below (except permission_type) are no-ops on the database.
        # They update recorded migration state from Python 2 b'' byte literals to Python 3
        # str, which Django's autodetector treats as field changes even though the schema
        # is identical.
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_cell',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cell phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_day',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Home phone'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_even',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternate phone'),
        ),
        migrations.AlterField(
            model_name='gradechangerequest',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='gradechangerequest',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        # permission_type also adds two new choices from SR16: Student/Waiver and
        # Teacher/Waiver (online liability waiver access). This is a real functional change,
        # not just a py3 string fix.
        migrations.AlterField(
            model_name='permission',
            name='permission_type',
            field=models.CharField(choices=[('Administer', 'Full administrative permissions'), ('View', 'Able to view a program'), ('Onsite', 'Access to onsite interfaces'), ('GradeOverride', 'Ignore grade ranges for studentreg'), ('OverrideFull', 'Register for a full program'), ('OverridePhaseZero', 'Bypass Phase Zero to proceed to other student reg modules'), ('Student Deadlines', (('Student/All', 'All student deadlines'), ('Student', 'Basic student access'), ('Student/MainPage', 'Registration mainpage'), ('Student/Profile', 'Set profile info'), ('Student/Acknowledgement', 'Student acknowledgement'), ('Student/FormstackMedliab', 'Access to Formstack medical and liability form'), ('Student/PhaseZero', 'Enter Phase Zero'), ('Student/Applications', 'Apply for classes'), ('Student/Classes', 'Register for classes'), ('Student/Classes/Lunch', 'Register for lunch'), ('Student/Classes/Lottery', 'Enter the lottery'), ('Student/Classes/Lottery/View', 'View lottery results'), ('Student/Confirm', 'Confirm registration'), ('Student/Cancel', 'Cancel registration'), ('Student/Removal', 'Remove class registrations after registration closes'), ('Student/Finaid', 'Access to financial aid application'), ('Student/ExtraCosts', 'Extra costs page'), ('Student/Payment', 'Pay for a program'), ('Student/Waiver', 'Access to online liability waiver'), ('Student/Webapp', 'Access to student onsite webapp'), ('Student/Survey', 'Access to survey'))), ('Teacher Deadlines', (('Teacher/All', 'All teacher deadlines'), ('Teacher', 'Basic teacher access'), ('Teacher/MainPage', 'Registration mainpage'), ('Teacher/Profile', 'Set profile info'), ('Teacher/Acknowledgement', 'Teacher acknowledgement'), ('Teacher/Availability', 'Set availability'), ('Teacher/Moderate', 'Fill out the moderator form'), ('Teacher/Events', 'Teacher training signup'), ('Teacher/Quiz', 'Teacher quiz'), ('Teacher/Catalog', 'Catalog'), ('Teacher/Classes/All', 'All classes deadlines'), ('Teacher/Classes/View', 'View registered classes'), ('Teacher/Classes/Edit', 'Edit registered classes'), ('Teacher/Classes/CancelReq', 'Request class cancellation'), ('Teacher/Classes/Coteachers', 'Add or remove coteachers'), ('Teacher/Classes/Create', 'Create classes of all types'), ('Teacher/Classes/Create/Class', 'Create standard classes'), ('Teacher/Classes/Create/OpenClass', 'Create open classes'), ('Teacher/AppReview', "Review students' apps"), ('Teacher/Waiver', 'Access to online liability waiver'), ('Teacher/Webapp', 'Access to teacher onsite webapp'), ('Teacher/Survey', 'Access to survey'))), ('Volunteer Deadlines', (('Volunteer', 'Basic volunteer access'), ('Volunteer/Signup', 'Volunteer signup')))], max_length=80),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='shirt_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='shirt_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
