# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_postal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Street address'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address_zip',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='e_mail',
            field=models.EmailField(blank=True, default='', max_length=75, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='educatorinfo',
            name='grades_taught',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='educatorinfo',
            name='position',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='educatorinfo',
            name='school',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='educatorinfo',
            name='subject_taught',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='k12school',
            name='contact_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='k12school',
            name='grades',
            field=models.TextField(blank=True, default='', help_text='i.e. "PK, K, 1, 2, 3"'),
        ),
        migrations.AlterField(
            model_name='k12school',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='k12school',
            name='school_id',
            field=models.CharField(blank=True, default='', help_text='An 8-digit ID number.', max_length=128),
        ),
        migrations.AlterField(
            model_name='k12school',
            name='school_type',
            field=models.TextField(blank=True, default='', help_text='i.e. Public, Private, Charter, Magnet, ...'),
        ),
        migrations.AlterField(
            model_name='persistentqueryfilter',
            name='useful_name',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='food_preference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='heard_about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='medical_needs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='pronoun',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='school',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='schoolsystem_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='shirt_size',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='shirt_type',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='studentrep_expl',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='college',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='graduation_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='major',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='pronoun',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='shirt_size',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='shirt_type',
            field=models.TextField(blank=True, default=''),
        ),
    ]
