# Generated by Django 2.2.28 on 2026-03-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforwarder',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forwarders_out', to='users.ESPUser'),
        ),
    ]
