# Generated by Django
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_permission_user_filter'),
        ('users', '0041_remove_passwordrecoveryticket'),
    ]

    operations = [
    ]
