# Generated by Django 2.2.28 on 2026-03-06 05:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_passwordrecoveryticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='If blank, has always started.', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='America/New_York', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.ESPUser')),
            ],
            options={
                'verbose_name_plural': 'User preferences',
            },
        ),
    ]
