# Generated by Django 2.2.28 on 2026-03-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_passwordrecoveryticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradechangerequest',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='from_here',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='is_graduate_student',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
