# Generated by Django 2.2.28 on 2026-04-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20260317_2119'),
        ('users', '0042_merge_2026_03_04'),
    ]

    operations = [
    ]

