# Generated by Django 2.2.28 on 2026-03-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20260306_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='timezone',
        ),
    ]
