# Generated by Django 2.2.28 on 2026-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20260317_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address_postal',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='undeliverable',
        ),
    ]
