# Generated by Django 2.2.28 on 2026-04-20 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20260327_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='If blank, has always started.', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
