# Generated by Django 2.2.28 on 2026-03-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20260326_1446'),
        ('users', '0043_auto_20260327_1528'),
    ]

    operations = [
    ]
