# Generated by Django 2.2.28 on 2026-04-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20260327_1528'),
        ('users', '0042_merge_2026_03_04'),
    ]

    operations = [
    ]

