# Generated by Django 2.2.28 on 2026-04-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20260327_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='can_view_schedule',
            field=models.BooleanField(default=True),
        ),
    ]
