# Generated by Django on 2026-05-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_contactinfo_address_country'),
        ('users', '0044_merge_20260425_1235'),
    ]

    operations = [
    ]
