# Generated by Django 4.2.30 on 2026-05-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_contactinfo_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='user_filter',
            field=models.ForeignKey(blank=True, help_text='Apply this permission to all users matching this saved filter.', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.persistentqueryfilter'),
        ),
    ]
