# Generated by Django 2.2.28 on 2026-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_k12school_city_k12school_state_alter_k12school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode'),
        ),
    ]
