# Generated by Django 4.2.30 on 2026-06-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_k12school_city_k12school_state_alter_k12school_name_and_more'),
        ('users', '0045_permission_user_filter'),
    ]

    operations = [
    ]
