# Generated by Django 5.2.14 on 2026-07-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_permission_user_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='user_filter',
            field=models.ForeignKey(blank=True, help_text='Apply this permission to all users matching this saved filter.', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.persistentqueryfilter'),
        ),
    ]
