# Generated by Django 5.2.15 on 2026-07-21 15:38

import django.db.models.deletion
import esp.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_permission_user_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforwarder',
            name='source',
            field=esp.db.fields.AjaxForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarders_out', to='users.espuser'),
        ),
    ]
