# Generated by Django 2.2.28 on 2026-03-07 01:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0041_remove_passwordrecoveryticket'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_action', 'Bulk action')], max_length=16)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the affected object.', null=True)),
                ('object_repr', models.TextField(blank=True, help_text='str() of the object at action time.')),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON dict of {field: [old_value, new_value]} for updates.', null=True)),
                ('extra', models.TextField(blank=True, help_text='Free-text note, e.g. bulk action name or extra context.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='Admin user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='users.ESPUser')),
                ('content_type', models.ForeignKey(blank=True, help_text='Django ContentType of the affected model.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
