# Generated by Django 2.2.28 on 2026-03-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_add_auditlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='actor_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the admin user at action time.', null=True),
        ),
    ]
