# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_auto_20151004_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementlink',
            name='section',
            field=models.CharField(blank=True, default='', help_text="e.g. 'teach' or 'learn' or blank", max_length=32),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fromemail',
            field=models.CharField(blank=True, default='', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='entry',
            name='section',
            field=models.CharField(blank=True, default='', help_text="e.g. 'teach' or 'learn' or blank", max_length=32),
        ),
    ]
