# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-21 21:04
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations

def set_my_defaults(apps, schema_editor):
    LineItemType = apps.get_model('accounting', 'LineItemType')
    LineItemType.objects.all().update(for_finaid=False)
    LineItemType.objects.filter(text='Program admission').update(for_finaid=True)

def reverse_func(apps, schema_editor):
    LineItemType = apps.get_model('accounting', 'LineItemType')
    LineItemType.objects.all().update(for_finaid=False)
    LineItemType.objects.filter(text__in=['Financial aid grant', 'Sibling discount']).update(for_finaid=True)

class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20210526_1921'),
    ]

    operations = [
        migrations.RunPython(set_my_defaults, reverse_func),
    ]
