# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-19 20:56
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20211221_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaidgrant',
            name='percent',
            field=models.PositiveIntegerField(blank=True, help_text='Enter an integer between 0 and 100 here to grant a certain percentage discount after the above dollar credit is applied.  0 means no additional discount, 100 means no payment is required for items that are covered by financial aid.', null=True),
        ),
        migrations.AlterField(
            model_name='lineitemtype',
            name='for_finaid',
            field=models.BooleanField(default=False, help_text='Should financial aid cover this line item?'),
        ),
    ]
