# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-19 21:14
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20220719_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemtype',
            name='amount_dec',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The cost of this line item.', max_digits=9),
        ),
    ]
