# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-11-21 21:56
from __future__ import unicode_literals

import json
import pickle

from django.db import migrations, models
from django.db.models.functions import Substr


def repair_legacy_answer_values(apps, schema_editor):
    """Fix up Answer rows created before this migration.

    Before this migration, Answer.value was hand-encoded with a sigil
    prefix instead of the value_type field: ':' + value for plain strings,
    '+' + pickle.dumps(value) for everything else (i.e. the lists used by
    Checkboxes/Favorite Class answers). The AddField above backfills
    value_type='str' for every existing row without accounting for this,
    which would otherwise leave the old sigil baked into `value` forever
    and never deserialize the pickled lists.
    """
    Answer = apps.get_model('survey', 'Answer')

    # Stripping the ':' prefix is a pure string operation, so do it as a
    # single UPDATE instead of a Python round-trip per row (~700k rows).
    Answer.objects.filter(value__startswith=':').update(value=Substr('value', 2))

    # Unpickling can't be pushed into SQL. Django 1.11 has no bulk_update(),
    # so batch the writes ourselves via a single "UPDATE ... CASE WHEN id"
    # per chunk instead of one UPDATE per row (~8k rows).
    #
    # Match on value_type != list rather than solely the '+' sigil: if this
    # migration is ever unapplied and reapplied (dev/test DBs get reset and
    # re-migrated often), AddField's backfill resets value_type to 'str' for
    # every row again, but a previously-repaired row's `value` no longer has
    # the '+' sigil to re-detect. Falling back to "does value already look
    # like a JSON list" makes this step idempotent.
    table = Answer._meta.db_table
    batch_size = 500
    ids_and_values = []
    for answer in Answer.objects.exclude(value_type="<class 'list'>").filter(
            models.Q(value__startswith='+') | models.Q(value__startswith='[')).iterator():
        if answer.value.startswith('+'):
            obj = pickle.loads(answer.value[1:].encode('latin1'))
        else:
            # Not necessarily pickle-derived: a free-text answer could
            # coincidentally start with '['. Only treat it as a repaired
            # list if it's actually valid JSON.
            try:
                obj = json.loads(answer.value)
            except ValueError:
                continue
        ids_and_values.append((answer.id, json.dumps(obj)))
    with schema_editor.connection.cursor() as cursor:
        for i in range(0, len(ids_and_values), batch_size):
            chunk = ids_and_values[i:i + batch_size]
            when_clauses = ' '.join('WHEN %s THEN %s' for _ in chunk)
            params = [param for id_, value in chunk for param in (id_, value)]
            ids_placeholder = ', '.join(['%s'] * len(chunk))
            cursor.execute(
                'UPDATE {table} SET value = CASE id {when} END, value_type = %s '
                'WHERE id IN ({ids_placeholder})'.format(
                    table=table, when=when_clauses, ids_placeholder=ids_placeholder),
                params + ["<class 'list'>"] + [id_ for id_, _ in chunk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20240509_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value_type',
            field=models.TextField(default='str'),
            preserve_default=False,
        ),
        migrations.RunPython(repair_legacy_answer_values, migrations.RunPython.noop),
    ]
