# Generated by Django 5.2.15 on 2026-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_answer_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="category",
            field=models.CharField(
                choices=[
                    ("learn", "learn"),
                    ("teach", "teach"),
                    ("generic", "generic"),
                ],
                max_length=10,
            ),
        ),
    ]
