# Generated by Django 2.2.28 on 2026-01-06 22:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210526_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstackappsettings',
            name='coreclass_fields',
            field=models.CharField(blank=True, help_text='A list of field ids separated by commas.', max_length=80, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
