# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0023_auto_20200730_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapGenModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
    ]
