# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 13:09
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations
import esp.program.modules.base


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0024_mapgenmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemsModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj', esp.program.modules.base.CoreModule),
        ),
    ]
