# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0025_lineitemsmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModeratorModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
    ]
