# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 09:45
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations

def set_my_defaults(apps, schema_editor):
    ProgramModule = apps.get_model('program', 'ProgramModule')
    old_pms = ProgramModule.objects.filter(handler="CustomFormModule")
    if old_pms.exists():
        for pm in old_pms:
            if pm.module_type == "teach":
                pm.handler = "TeacherCustomFormModule"
                pm.link_title = "Additional Teacher Information"
            else:
                pm.handler = "StudentCustomFormModule"
                pm.link_title = "Additional Student Information"
            pm.save()

def reverse_func(apps, schema_editor):
    ProgramModule = apps.get_model('program', 'ProgramModule')
    pms = ProgramModule.objects.filter(handler="StudentCustomFormModule")
    if pms.count() == 1:
        new_pm1 = pms[0] if pms.count() == 1 else None
    pms = ProgramModule.objects.filter(handler="TeacherCustomFormModule")
    if pms.count() == 1:
        new_pm2 = pms[0] if pms.count() == 1 else None
    for pm in [new_pm1, new_pm2]:
        pm.handler = "CustomFormModule"
        pm.link_title = "Additional Profile Information"
        pm.save()

class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0028_auto_20210518_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCustomFormModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.CreateModel(
            name='TeacherCustomFormModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.DeleteModel(
            name='CustomFormModule',
        ),
    ]
