# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-16 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0032_delete_textmessagemodule'),
        ('modules', '0026_auto_20230104_0119'),
    ]

    operations = [
    ]
