# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-09 20:12
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0033_regprofile_availability_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecordsModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
    ]
