# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-28 11:13
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0037_medliab_split'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SplashInfoModule',
        ),
    ]
