# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-18 20:41
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0038_delete_splashinfomodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
    ]
