# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-25 20:43
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0040_auto_20220719_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='use_grade_range_exceptions',
            field=models.BooleanField(default=False, help_text=b'Check this box to enable grade range exceptions for the two-phase class lottery.'),
        ),
    ]
