# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-05 20:47
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0041_auto_20230525_2043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingLabels',
        ),
    ]
