# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0041_auto_20230525_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='use_grade_range_exceptions',
            field=models.BooleanField(default=False, help_text='Check this box to enable grade range exceptions for the two-phase class lottery.'),
        ),
    ]
