# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 23:41
from __future__ import unicode_literals

from __future__ import absolute_import
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0043_auto_20240321_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLabels',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='color_code',
            field=models.CharField(blank=True, help_text='The background color for class titles in the catalog and registration pages. If no color is chosen, the default light blue will be used.', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#([a-zA-Z0-9]{3}){1,2}$', message='Value must be a valid 3-character or 6-character hex color starting with "#".')]),
        ),
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='use_grade_range_exceptions',
            field=models.BooleanField(default=False, help_text='Check this box to enable grade range exceptions for the two-phase class lottery.'),
        ),
    ]
