# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-07 20:41
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0043_auto_20240321_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='send_confirmation',
            field=models.BooleanField(default=True, help_text='Check this box to send each student an email each time they confirm their registration. You can customize the text of the email using the "Confirmemail" registration receipt below.'),
        ),
    ]
