# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-15 20:25
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0044_auto_20240507_2041'),
        ('modules', '0044_auto_20240509_2341'),
    ]

    operations = [
    ]
