# Generated by Django 2.2.28 on 2026-01-06 22:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0045_merge_20240515_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='allow_coteach',
            field=models.BooleanField(blank=True, default=True, help_text='Check this box to allow teachers to specify co-teachers.'),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='allow_lateness',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='allowed_sections',
            field=models.CharField(blank=True, help_text='Allow this many independent sections of a class (comma separated list of integers). Leave blank to allow arbitrarily many.', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='ask_for_room',
            field=models.BooleanField(blank=True, default=True, help_text='If true, teachers will be asked if they have a particular classroom in mind.'),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_other_sizes',
            field=models.CharField(blank=True, help_text="Force the addition of these options to teachers' choices of class size.  (Enter a comma-separated list of integers.)", max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='open_class_registration',
            field=models.BooleanField(blank=True, default=False, help_text='If true, teachers will be presented with an option to register for an "open class".'),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='session_counts',
            field=models.CharField(blank=True, help_text='Possibilities for the number of days that a class could meet (comma separated list of integers). Leave blank if this is not a relevant choice for the teachers.', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='set_prereqs',
            field=models.BooleanField(blank=True, default=True, help_text='Check this box to allow teachers to enter prerequisites for each class that are displayed separately on the catalog.'),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='use_allowable_class_size_ranges',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='use_class_size_max',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='use_class_size_optimal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='use_optimal_class_size_range',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
