# Generated by Django 2.2.28 on 2026-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0046_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='apply_multiplier_to_room_cap',
            field=models.BooleanField(default=False, help_text='Apply class cap multiplier and offset to room capacity instead of class capacity.'),
        ),
    ]
