# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0046_merge_20260426'),
    ]

    operations = [
        # CheckAvailabilityModule was created as a proxy in 0017, then MIT deleted it in
        # 0025_delete_checkavailabilitymodule as a temporary workaround to support the
        # MIT-specific "observers" field. LU re-added proxy=True to the handler in
        # commit f313fd4ab (merged into sr15) without a matching re-create migration on
        # the MIT side, leaving the migration chain out of sync with the handler.
        # The observers workaround is now gone (data moved to moderators), so we
        # re-create the proxy to match LU's expected state.
        migrations.CreateModel(
            name='CheckAvailabilityModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        # The remaining AlterField operations are no-ops on the database. They update the
        # recorded migration state from Python 2 b'' byte literals to Python 3 str, which
        # Django's autodetector treats as field changes even though the schema is identical.
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='ask_for_room',
            field=models.BooleanField(default=False, help_text='If true, teachers will be asked if they have a particular classroom in mind.'),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_max_duration',
            field=models.IntegerField(blank=True, help_text='The maximum length of a class, in minutes. Typically set to 80 for HSSPs and 170 for Splarks.', null=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_max_size',
            field=models.IntegerField(default=5, help_text='The maximum number of students a teacher can choose as their class capacity.', null=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_min_cap',
            field=models.IntegerField(default=5, help_text='The minimum number of students a teacher can choose as their class capacity.', null=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_min_duration',
            field=models.IntegerField(blank=True, help_text='The minimum length of a class, in minutes. Typically set to 50 for HSSPs and left blank for Splarks.', null=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_other_sizes',
            field=models.CommaSeparatedIntegerField(default='7,10,12,15,20,30,50,75,100,150,200', help_text="Force the addition of these options to teachers' choices of class size.  (Enter a comma-separated list of integers.)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_size_step',
            field=models.IntegerField(default=1, help_text='The interval for class capacity choices.', null=True),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='open_class_registration',
            field=models.BooleanField(default=False, help_text='If true, teachers will be presented with an option to register for walk-in classes.'),
        ),
    ]
