# Generated by Django 2.2.28 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0046_auto_20260106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassregmoduleinfo',
            name='enable_class_waitlist',
            field=models.BooleanField(default=False, help_text='Check this box to enable per-section waitlisting when classes are full. Students can join a waitlist and be auto-enrolled when a spot opens.'),
        ),
        migrations.AddField(
            model_name='studentclassregmoduleinfo',
            name='max_waitlist_per_timeslot',
            field=models.IntegerField(default=1, help_text='Maximum number of classes a student can waitlist per time block.'),
        ),
    ]
