# Generated by Django 2.2.28 on 2026-03-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0047_waitlist_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='apply_multiplier_to_room_cap',
            field=models.BooleanField(default=False, help_text='Apply class cap multiplier and offset to room capacity instead of class capacity.'),
        ),
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='enable_class_waitlist',
            field=models.BooleanField(default=True, help_text='Uncheck this box to disable per-section waitlisting when classes are full. When enabled, students can join a waitlist and be auto-enrolled when a spot opens.'),
        ),
    ]
