# -*- coding: utf-8 -*-
# Generated by Django 2.2.28 on 2026-02-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0047_add_admintestingmodule'),
        ('modules', '0047_programmoduleobj_link_title'),
    ]

    operations = [
    ]
