# Generated by Django 2.2.28 on 2026-03-02 00:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0047_programmoduleobj_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='class_other_sizes',
            field=models.CharField(blank=True, default='', help_text="Force the addition of these options to teachers' choices of class size.  (Enter a comma-separated list of integers.)", max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='classregmoduleinfo',
            name='color_code',
            field=models.CharField(blank=True, default='', help_text='The background color for class titles in the catalog and registration pages. If no color is chosen, the default light blue will be used.', max_length=7, validators=[django.core.validators.RegexValidator('^#([a-zA-Z0-9]{3}){1,2}$', message='Value must be a valid 3-character or 6-character hex color starting with "#".')]),
        ),
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='apply_multiplier_to_room_cap',
            field=models.BooleanField(default=False, help_text='Apply class cap multiplier and offset to room capacity instead of class capacity.'),
        ),
    ]
