# Generated by Django 2.2.28 on 2026-03-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0049_remove_adminmorph'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTestingModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.AlterField(
            model_name='studentclassregmoduleinfo',
            name='apply_multiplier_to_room_cap',
            field=models.BooleanField(default=False, help_text='Apply class cap multiplier and offset to room capacity instead of class capacity.'),
        ),
    ]
