# Generated by Django 2.2.28 on 2026-03-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0049_remove_adminmorph'),
        ('modules', '0048_auto_20260302_0348'),
    ]

    operations = [
    ]
