# Generated by Django 2.2.28 on 2026-03-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0050_merge_20260307_0349'),
        ('modules', '0050_auto_20260306_0001'),
    ]

    operations = [
    ]
