# Generated by Django 2.2.28 on 2026-03-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0050_merge_20260307_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajaxchangelogentry',
            name='assigned',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ajaxchangelogentry',
            name='locked',
            field=models.BooleanField(null=True),
        ),
    ]
