# Generated by Django on 2026-03-21

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0051_merge_20260311_1522'),
        ('modules', '0051_auto_20260317_2119'),
    ]

    operations = [
    ]
