# Generated by Django 2.2.28 on 2026-03-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0051_auto_20260317_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTestingModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.CreateModel(
            name='BatchClassRegModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.programmoduleobj',),
        ),
    ]
