# Generated by Django 2.2.28 on 2026-03-26 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0051_auto_20260317_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTestingModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.CreateModel(
            name='BatchClassRegModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.programmoduleobj',),
        ),
        migrations.AddField(
            model_name='programmoduleobj',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, help_text='If blank, never ends.', null=True),
        ),
        migrations.AddField(
            model_name='programmoduleobj',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='If blank, has always started.', null=True),
        ),
    ]
