# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0048_teacher_email_rules'),
        ('modules', '0051_auto_20260317_2119'),
    ]

    operations = [
    ]
