# Generated by Django 2.2.28 on 2026-03-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0052_admintestingmodule_batchclassregmodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingLabels',
        ),
    ]
