# Generated by Django 2.2.28 on 2026-04-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0053_delete_mailinglabels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedBudgetModule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modules.programmoduleobj',),
        ),
    ]
