# Generated by Django 2.2.28 on 2026-04-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0053_delete_mailinglabels'),
        ('modules', '0051_admintestingmodule_batchclassregmodule'),
    ]

    operations = [
    ]
