# Generated by Django 2.2.28 on 2026-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0052_merge_20260321_0030'),
        ('modules', '0053_delete_mailinglabels'),
    ]

    operations = [
    ]
