# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0052_merge_teacher_email_rules'),
        ('modules', '0054_programmoduleobj_expirable'),
    ]

    operations = [
    ]
