# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-28 16:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.fields
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_regtype_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='custom_form_data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
    ]
