# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 09:06
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_auto_20210318_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsection',
            name='ever_checked_in_students',
        ),
    ]
