# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-16 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0024_auto_20210617_0928'),
        ('program', '0021_auto_20230104_0119'),
    ]

    operations = [
    ]
