# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-22 21:00
from __future__ import unicode_literals

from __future__ import absolute_import
import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0025_auto_20220719_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcategories',
            name='symbol',
            field=models.CharField(default='Z', help_text='A single letter to represent the category', max_length=1, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1}', 'Must be a single letter.')]),
        ),
    ]
