# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-09 13:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0026_auto_20221122_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
    ]
