# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-09 23:41
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0027_auto_20240220_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='class_categories',
            field=models.ManyToManyField(blank=True, help_text='You can add new categories or modify existing ones <a href="/manage/catsflagsrecs/categories">here</a>.', to='program.ClassCategories'),
        ),
        migrations.AlterField(
            model_name='program',
            name='flag_types',
            field=models.ManyToManyField(blank=True, help_text='The set of flags that can be used to tag classes for this program. You can add and modify flag types <a href="/manage/catsflagsrecs/flagtypes">here</a>.', to='program.ClassFlagType'),
        ),
    ]
