# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-06-18 21:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0029_merge_20260426'),
    ]

    operations = [
        # Drop the MIT-specific observers M2M field. Data was already copied to the
        # LU-standard moderators field by 0026_copy_observers_to_moderators.
        migrations.RemoveField(
            model_name='classsection',
            name='observers',
        ),
        # The remaining AlterField operations update recorded migration state from Python 2
        # b'' byte literals (and missing validators/null attrs) to the current model
        # definition. No actual database schema changes.
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_cc_email',
            field=models.EmailField(blank=True, default='', help_text='If set, automated outgoing mail (except class cancellations) will be sent to this address <i>instead of</i> the director email. Use this if you do not want to spam the director email with teacher class registration emails. Otherwise, leave this field blank.', max_length=75),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_confidential_email',
            field=models.EmailField(blank=True, default='', help_text='If set, confidential emails such as financial aid applications will be sent to this address <i>instead of</i> the director email.', max_length=75),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(help_text='The "director email" should be the public-facing email address for the program (e.g. splash@mit.edu). It should usually <i>not</i> be a directors-only email address.', max_length=75, validators=[django.core.validators.RegexValidator('(^.+@esp\\.mit\\.edu$)|(^.+@mit\\.edu$)|(^.+@esp-dev\\.mit\\.edu$)', message='Domain must match one of: esp\\.mit\\.edu, mit\\.edu, esp-dev\\.mit\\.edu')]),
        ),
    ]
