# Generated by Django 2.2.28 on 2026-01-06 22:04

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0029_migrate_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='reduced_lunch',
            field=models.BooleanField(blank=True, default=False, verbose_name='Do you receive free/reduced lunch at school?'),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='student_prepare',
            field=models.BooleanField(blank=True, default=False, verbose_name='Did anyone besides the student fill out any portions of this form?'),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(default='info@devsite.learningu.org', help_text='The director email address must end in @devsite.learningu.org (your website), @learningu.org, or a valid subdomain of learningu.org (i.e., @subdomain.learningu.org). The default is <b>info@devsite.learningu.org</b>, which redirects to the "default" email address from your site\'s settings by default. You can create and manage your email redirects <a href="/manage/redirects/">here</a>.', max_length=75, validators=[django.core.validators.RegexValidator('(^.+@devsite\\.learningu\\.org$)|(^.+@(\\w+\\.)?learningu\\.org$)')]),
        ),
    ]
