# Generated by Django 2.2.28 on 2026-03-01 17:28

from django.db import migrations, models
import django.db.models.deletion
import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20260106_2204'),
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='classflag',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classflag',
            name='resolved_by',
            field=esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classflags_resolved', to='users.ESPUser'),
        ),
        migrations.AddField(
            model_name='classflag',
            name='resolved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
