# Generated by Django 2.2.28 on 2026-03-06 05:01

from django.db import migrations, models
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Is this an online program?'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentappreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='If blank, has always started.', null=True),
        ),
        migrations.AlterField(
            model_name='studentsubjectinterest',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='If blank, has always started.', null=True),
        ),
    ]
