# Generated by Django 2.2.28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='classflagtype',
            name='show_to_teacher',
            field=models.BooleanField(default=False, help_text='Should this flag type be visible to teachers of the flagged class?'),
        ),
        migrations.AddField(
            model_name='classflagtype',
            name='notify_teacher_by_email',
            field=models.BooleanField(default=False, help_text='Should teachers be emailed when a flag of this type is added to their class?'),
        ),
    ]
