# Generated by Django 2.2.28 on 2026-03-02 00:17

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveclass',
            name='teacher_ids',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='class_style',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='directors_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='hardness_rating',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='prereqs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='purchase_requests',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='requested_room',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classsubject',
            name='requested_special_resources',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='financialaidrequest',
            name='extra_explaination',
            field=models.TextField(blank=True, default='', verbose_name='Please describe in detail your financial situation this year'),
        ),
        migrations.AlterField(
            model_name='moderatorrecord',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='inline_template',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='link_title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='displayName',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='splashinfo',
            name='lunchsat',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='splashinfo',
            name='lunchsun',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='splashinfo',
            name='siblingname',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='teacherbio',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacherbio',
            name='slugbio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteeroffer',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='volunteeroffer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='volunteeroffer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='volunteeroffer',
            name='shirt_size',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='volunteeroffer',
            name='shirt_type',
            field=models.TextField(blank=True, default=''),
        ),
    ]
