# Generated by Django 2.2.28 on 2026-03-11 03:38

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='class_categories',
            field=models.ManyToManyField(blank=True, help_text='You can <a href="/manage/catsflagsrecs/categories">add new categories or modify existing ones</a>.', to='program.ClassCategories'),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(default='info@devsite.learningu.org', help_text='The director email address must end in @devsite.learningu.org (your website), @learningu.org, or a valid subdomain of learningu.org (i.e., @subdomain.learningu.org). The default is <b>info@devsite.learningu.org</b>, which redirects to the "default" email address from your site\'s settings by default. You can <a href="/manage/redirects/">create and manage your email redirects </a>.', max_length=75, validators=[django.core.validators.RegexValidator('(^.+@devsite\\.learningu\\.org$)|(^.+@(\\w+\\.)?learningu\\.org$)')]),
        ),
        migrations.AlterField(
            model_name='program',
            name='flag_types',
            field=models.ManyToManyField(blank=True, help_text='The set of flags that can be used to tag classes for this program. You can <a href="/manage/catsflagsrecs/flagtypes">add and modify flag types</a>.', to='program.ClassFlagType'),
        ),
    ]
