# Generated by Django 2.2.28 on 2026-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='allowable_class_size_ranges',
            field=models.ManyToManyField(blank=True, related_name='classsubject_allowedsizes', to='program.ClassSizeRange'),
        ),
    ]
