# Generated by Django 2.2.28 on 2026-02-20 00:00

from django.db import migrations, models
import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dbmail", "0010_textofemail_messagerequest"),
        ("program", "0030_auto_20260106_2204"),
        ("users", "0040_auto_20260106_2204"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquityOutreachCampaign",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cohort_key", models.CharField(max_length=64)),
                ("cohort_label", models.CharField(max_length=128)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=16)),
                ("subject", models.CharField(blank=True, default="", max_length=256)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("created_by", esp.db.fields.AjaxForeignKey(on_delete=models.deletion.CASCADE, to="users.ESPUser")),
                ("message_request", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to="dbmail.MessageRequest")),
                ("program", models.ForeignKey(on_delete=models.deletion.CASCADE, to="program.Program")),
            ],
            options={"app_label": "program"},
        ),
        migrations.CreateModel(
            name="EquityOutreachRecipient",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS")], max_length=16)),
                ("destination", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped")],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("campaign", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="recipients", to="program.EquityOutreachCampaign")),
                ("user", esp.db.fields.AjaxForeignKey(on_delete=models.deletion.CASCADE, to="users.ESPUser")),
            ],
            options={"app_label": "program"},
        ),
        migrations.AlterUniqueTogether(
            name="equityoutreachrecipient",
            unique_together={("campaign", "user", "channel")},
        ),
    ]

