# Generated by Django 2.2.28 on 2026-03-05 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_passwordrecoveryticket'),
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='course_materials_url',
            field=models.URLField(blank=True, help_text='Link to course materials', null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='course_website',
            field=models.URLField(blank=True, help_text='Link to the course website', null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='instructor_email',
            field=models.EmailField(blank=True, help_text='Instructor contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='classsection',
            name='instructor_phone',
            field=models.CharField(blank=True, help_text='Instructor contact phone', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClassCheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='checked-in', max_length=32)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='program.ClassSection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='users.ESPUser')),
            ],
            options={
                'db_table': 'program_classcheckin',
                'unique_together': {('student', 'class_section', 'status')},
            },
        ),
    ]
