# Generated by Django 2.2.28 on 2026-03-01 17:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20260106_2204'),
        ('program', '0030_auto_20260106_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='classflag',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classflag',
            name='resolved_by',
            field=esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classflags_resolved', to='users.ESPUser'),
        ),
        migrations.AddField(
            model_name='classflag',
            name='resolved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(default='info@testserver.learningu.org', help_text='The director email address must end in @testserver.learningu.org (your website), @learningu.org, or a valid subdomain of learningu.org (i.e., @subdomain.learningu.org). The default is <b>info@testserver.learningu.org</b>, which redirects to the "default" email address from your site\'s settings by default. You can create and manage your email redirects <a href="/manage/redirects/">here</a>.', max_length=75, validators=[django.core.validators.RegexValidator('(^.+@testserver\\.learningu\\.org$)|(^.+@(\\w+\\.)?learningu\\.org$)')]),
        ),
    ]
