# Generated by Django 2.2.28 on 2026-02-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0031_equity_outreach_campaign"),
    ]

    operations = [
        migrations.DeleteModel(name="EquityOutreachRecipient"),
        migrations.DeleteModel(name="EquityOutreachCampaign"),
    ]
