# Generated by Django 2.2.28 on 2026-03-01 18:00

from django.db import migrations
import django.db.models.deletion
import esp.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_auto_20260301_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classflag',
            name='created_by',
            field=esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classflags_created', to='users.ESPUser'),
        ),
        migrations.AlterField(
            model_name='classflag',
            name='modified_by',
            field=esp.db.fields.AjaxForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classflags_modified', to='users.ESPUser'),
        ),
    ]
