# Generated by Django 2.2.28 on 2026-03-11 14:37

from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_auto_20260305_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
    ]
