# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-08-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_py3_string_fixes'),
        ('program', '0031_add_checkavailabilitymodule_to_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotteryInputSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_input_snapshots', to='program.Program')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solver_name', models.CharField(max_length=64)),
                ('solver_job_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('interrupted', 'Interrupted'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('params', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress_series', django_extensions.db.fields.json.JSONField(blank=True, default=list, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_pairs', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_runs', to='program.Program')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.ESPUser')),
                ('snapshot', models.ForeignKey(db_column='input_hash', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='program.LotteryInputSnapshot', to_field='input_hash')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.ESPUser')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
