# Generated by Django 2.2.28 on 2026-03-12 08:03

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_auto_20260302_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, help_text='Additional categories this class can appear under', related_name='secondary_classsubjects', to='program.ClassCategories'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
    ]
