# Generated by Django 2.2.28 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_auto_20260302_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsection',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
