# Generated by Django 3.2.18 on 2026-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0032_auto_20260302_0348'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('user', 'section', 'relationship'), name='unique_active_enrollment'),
        ),
    ]
