# Generated by Django 2.2.28 on 2026-03-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_auto_20260306_0001'),
        ('program', '0032_auto_20260302_0348'),
    ]

    operations = [
    ]
