# Generated by Django 2.2.28 on 2026-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_merge_20260311_1523'),
        ('program', '0033_cleanup_duplicate_registration_profiles'),
    ]

    operations = [
    ]
