# Generated by Django 2.2.28 on 2026-03-17 21:19

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0033_cleanup_duplicate_registration_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='old_text_reminder',
            field=models.BooleanField(db_column='text_reminder', null=True),
        ),
        migrations.AlterField(
            model_name='splashinfo',
            name='siblingdiscount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='splashinfo',
            name='submitted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
