# Generated by Django 2.2.28 on 2026-03-26 03:42

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_auto_20260317_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(default='info@devsite.learningu.org', help_text='The director email address must end in @devsite.learningu.org (your website), @learningu.org, or a valid subdomain of learningu.org (i.e., @subdomain.learningu.org). The default is <b>info@devsite.learningu.org</b>, which redirects to the "default" email address from your site\'s settings by default. You can create and manage your email redirects <a href="/manage/redirects/">here</a>.', max_length=75, validators=[django.core.validators.RegexValidator('(^.+@devsite.learningu.org$)|(^.+@(\\w+\\.)?learningu\\.org$)')]),
        ),
    ]
