# Generated by Django on 2026-03-21

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_auto_20260317_2119'),
        ('program', '0034_merge_20260316_1338'),
    ]

    operations = [
    ]
