# Generated by Django 2.2.28 on 2026-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_auto_20260317_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(max_length=75),
        ),
    ]
