# Generated by Django 2.2.28 on 2026-03-25 18:52

from django.db import migrations, models
import esp.program.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0034_auto_20260317_2119'),
    ]

    operations = []
