# Generated by Django 2.2.28 on 2026-04-02 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0035_auto_20260326_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodule',
            name='admin_title',
            field=models.CharField(help_text='Title shown in the admin interface', max_length=128),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='choosable',
            field=models.IntegerField(default=0, help_text='Controls whether users can choose this module', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='handler',
            field=models.CharField(help_text='Handler used to process this module', max_length=32),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='inline_template',
            field=models.CharField(blank=True, help_text='Template used to render this module inline', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='link_title',
            field=models.CharField(blank=True, help_text='Optional title displayed for this module link', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='module_type',
            field=models.CharField(help_text='Defines how this module is used (e.g., teach, learn, manage, onsite). See <a href="https://github.com/learning-unlimited/ESP-Website/blob/main/docs/admin/program_modules.rst" target="_blank">Program Modules documentation</a> for details.', max_length=32),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='required',
            field=models.BooleanField(default=False, help_text='Whether this module is required for completion'),
        ),
        migrations.AlterField(
            model_name='programmodule',
            name='seq',
            field=models.IntegerField(help_text='Order in which this module appears'),
        ),
    ]
