# Generated by Django 2.2.28 on 2026-03-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0035_auto_20260327_1923'),
        ('program', '0035_auto_20260326_1003'),
    ]

    operations = [
    ]
