# Generated by Django 2.2.28 on 2026-03-21 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0035_auto_20260321_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsection',
            name='attending_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='enrolled_students',
            field=django.db.models.fields.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]+$', 'Program URL can only contain lowercase letters, numbers, and hyphens (no spaces).')]),
        ),
    ]
