# Generated by Django 2.2.28 on 2026-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0035_auto_20260325_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='director_email',
            field=models.EmailField(max_length=75),
        ),
    ]
