# Generated by Django 2.2.28 on 2026-04-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0036_auto_20260402_0614'),
        ('program', '0036_auto_20260402_0802'),
    ]

    operations = [
    ]
