# Generated by Django 2.2.28

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    ClassCategories = apps.get_model("program", "ClassCategories")
    for category in ClassCategories.objects.all():
        if category.category and category.category.lower() == 'lunch':
            category.is_lunch = True
            category.save()

def backwards_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_auto_20260402_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcategories',
            name='is_lunch',
            field=models.BooleanField(default=False, help_text='True if this category represents Lunch'),
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]
