# Generated by Django 2.2.28

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    ClassCategories = apps.get_model("program", "ClassCategories")
    ClassCategories.objects.filter(category__iexact='lunch').update(is_lunch=True)

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_auto_20260402_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcategories',
            name='is_lunch',
            field=models.BooleanField(default=False, help_text='True if this category represents Lunch'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
