# Generated by Django on 2026-04-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0031_printablejob'),
        ('program', '0037_auto_20260402_2109'),
    ]

    operations = [
    ]
