# Generated by Django 2.2.28 on 2026-04-12 01:17

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_auto_20260402_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='picture',
            field=models.ImageField(blank=True, height_field='picture_height', null=True, upload_to='uploaded/class_pictures/%y_%m/', width_field='picture_width'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='picture_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='picture_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
