# Generated by Django 2.2.28 on 2026-04-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_auto_20260402_2109'),
        ('program', '0035_merge_20260321_0030'),
    ]

    operations = [
    ]
