# Generated by manual intervention on 2026-03-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_auto_20260402_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTestSubject',
            fields=[
                ('booleantoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='program.BooleanToken')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.ClassSubject')),
            ],
            options={
                'app_label': 'program',
            },
            bases=('program.booleantoken',),
        ),
    ]
