# Generated by Django 2.2.28 on 2026-04-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0037_auto_20260402_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubject',
            name='extended_budget_status',
            field=models.IntegerField(choices=[(0, 'Not requested'), (10, 'Pending'), (20, 'Approved'), (30, 'Rejected')], db_index=True, default=0),
        ),
    ]
