# Generated by Django 2.2.28 on 2026-04-05 00:00

from django.db import migrations


def populate_extended_budget_status(apps, schema_editor):
    # Intentionally do not backfill from purchase_requests.
    # That field predates the extended-budget workflow and was used for
    # general planned/reimbursable supplies, so treating legacy text as an
    # explicit request would create noisy false-positive pending requests.
    pass


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0038_classsubject_extended_budget_status'),
    ]

    operations = [
        migrations.RunPython(populate_extended_budget_status, noop_reverse),
    ]
