# Generated by Django 2.2.28 on 2026-04-05 00:00

from django.db import migrations


def populate_extended_budget_status(apps, schema_editor):
    ClassSubject = apps.get_model('program', 'ClassSubject')
    for cls in ClassSubject.objects.filter(extended_budget_status=0).exclude(purchase_requests__isnull=True):
        if cls.purchase_requests and cls.purchase_requests.strip():
            cls.extended_budget_status = 10  # Pending
            cls.save(update_fields=['extended_budget_status'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0038_classsubject_extended_budget_status'),
    ]

    operations = [
        migrations.RunPython(populate_extended_budget_status, noop_reverse),
    ]
