# Generated by Django 3.2.25 on 2026-05-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0038_autoclassflagrule'),
        ('program', '0039_populate_extended_budget_status'),
    ]

    operations = []
