# Generated by Django 5.2.15 on 2026-07-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0036_auto_20260326_1446'),
        ('program', '0040_printablejob'),
    ]

    operations = [
    ]
