# Generated by Django 3.2.25 on 2026-05-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0040_merge_0038_autoclassflagrule_0039_populate_extended_budget_status'),
        ('program', '0040_printablejob'),
    ]

    operations = []
