# Generated by Django 2.2.28 on 2026-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0040_merge_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='allowable_class_size_ranges',
            field=models.ManyToManyField(blank=True, related_name='classsubject_allowedsizes', to='program.ClassSizeRange'),
        ),
    ]
