# Generated by Django 5.2.15 on 2026-07-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0040_printablejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='allowable_class_size_ranges',
            field=models.ManyToManyField(blank=True, related_name='classsubject_allowedsizes', to='program.classsizerange'),
        ),
    ]
