# Generated by Django 5.2.15 on 2026-08-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0042_classcategories_is_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasezerorecord',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program'),
        ),
    ]
