# Generated by Django on program model name and url validators

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0044_alter_program_name_alter_program_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(
                help_text='The full name of the program.',
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Program name may only contain alphanumeric characters, spaces, and hyphens.',
                        regex='^[a-zA-Z0-9 -]+$',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.SlugField(
                help_text='The URL fragment for this program.',
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Program URL may only contain lowercase alphanumeric characters and hyphens.',
                        regex='^[a-z0-9-]+$',
                    )
                ],
            ),
        ),
    ]
