name: "Migration Consistency Check"

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read


jobs:
  migrations:
    name: Migration Consistency Check
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: test_django
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      memcached:
        image: memcached:alpine
        ports:
          - 11211:11211
    env:
      DJANGO_SETTINGS_MODULE: esp.settings
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Cache pip packages
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.12-${{ hashFiles('esp/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.12-
          ${{ runner.os }}-pip-
    - name: Get apt packages list
      id: apt-action-migrations
      run: |
        PKGS=$(cat esp/packages_base.txt | grep -v '^memcached' | grep -v '^postgres' | grep -v '^libpq-dev' | grep -v '^.*pip' | tr '\n' ' ')
        echo "packages=$PKGS" >> $GITHUB_OUTPUT
    - name: Cache apt packages
      uses: Eeems-Org/apt-cache-action@v1
      with:
        packages: ${{ steps.apt-action-migrations.outputs.packages }}
    - name: Prepare for Installing Dependencies
      run: deploy/ci/before_install
      env:
        PYTHON_VERSION: "3.12"
    - name: Install Dependencies
      env:
        CI_JOB: test
        PYTHON_VERSION: "3.12"
      run: deploy/ci/install
    - name: Prepare for Migration Check
      env:
        CI_JOB: test
        PYTHON_VERSION: "3.12"
      run: deploy/ci/before_script
    - name: Run Migration Check
      env:
        DATABASE_USER: testuser
        DATABASE_PASSWORD: testpassword
        DATABASE_NAME: test_django
      run: |
        cd esp
        python manage.py makemigrations --check --dry-run
