# Lists of all tags used anywhere in the codebase
# Populated by hand, so don't be too surprised if something
# is missing

# Format: 'key': "some help text for admins"

# Any tag used with Tag.getTag()
all_global_tags = {
    'teacherreg_custom_forms': "",
    'allow_global_restypes': "Include global resource types in the options shown",
    'splashinfo_choices': "",
    'full_group_name': "",
    'nearly_full_threshold': "",
    'splashinfo_siblingdiscount': "",
    'splashinfo_lunchsat': "",
    'splashinfo_lunchsun': "",
    'use_class_size_optimal': "",
    'teacherreg_difficulty_choices': "",
    'volunteer_tshirt_options': "",
    'volunteer_tshirt_type_selection': "",
    'volunteer_allow_comments': "",
    'min_available_timeslots': "",
    'availability_group_timeslots': "Group timeslots into contiguous blocks in the availability interface (enabled by default, set to 'False' to disable)",
    'formstack_id': "",
    'formstack_viewkey': "",
    'group_phone_number': "",
    'finaid_form_fields': "",
    'onsite_classlist_min_refresh': "",
    'studentschedule_show_empty_blocks': "",
    'oktimes_collapse': "",
    'qsd_display_date_author': "",
    'current_theme_name': "",
    'prev_theme_customization': "",
    'current_theme_params': "",
    'theme_template_control': "",
    'current_theme_palette': "",
    'request_student_phonenum': "",
    'allow_change_grade_level': "",
    'show_studentrep_application': "",
    'show_student_tshirt_size_options': "",
    'show_student_vegetarianism_options': "",
    'show_student_graduation_years_not_grades': "",
    'ask_student_about_transportation_to_program': "",
    'student_medical_needs': "",
    'require_school_field': "",
    'teacherinfo_shirt_options': "",
    'teacherinfo_shirt_type_selection': "",
    'teacher_profile_hide_fields': "",
    'student_grade_options': "",
    'user_types': "",
    'studentinfo_shirt_options': "",
    'studentinfo_food_options': "",
    'ask_about_duplicate_accounts': "",
    'require_email_validation': "",
}

# Any tag used with Tag.getBooleanTag()
all_boolean_tags = {
    'increment_default_grade_levels': "Consider all students to be one grade level higher (useful for summer programs)",
    'student_profile_gender_field': "Ask about student gender in profile",
    'ask_about_duplicate_accounts': "Before creating an account for an email address already in the database, ask if the user wants to log into an existing account instead",
    'require_email_validation': "",
    'automatic_registration_redirect': "If student/teacher registration is open for exactly one program, redirect to student registration after student account creation (enabled by default)",
    'friendly_times_with_date': "",
}

# Any tag used with Tag.getProgramTag(),
# or Tag.getBooleanTag() with a program argument
all_program_tags = {
    'open_class_category': "Class category used for open classes (classes for which students don't register in advance)",
    'sibling_discount': "",
    'splashinfo_costs': "",
    'catalog_sort_fields': "",
    'teacherreg_hide_fields': "",
    'teacherreg_default_min_grade': "",
    'teacherreg_default_max_grade': "",
    'teacherreg_default_class_size_max': "",
    'stripe_settings': "",
    'learn_extraform_id': "",
    'teach_extraform_id': "",
    'donation_settings': "",
    'splashinfo_choices': "",
    'no_overlap_classes': "",
    'special_classroom_types': "",
    'collapse_full_classes': "",
    'friendly_times_with_date': "",
    'grade_range_popup': "",
    'quiz_form_id': "",
    'default_restypes': "",
    'cc_redirect': "",
    'increment_default_grade_levels': "",
    'teacherreg_help_text_duration': "",
    'teacherreg_help_text_class_size_max': "",
    'teacherreg_help_text_num_sections': "",
    'teacherreg_help_text_requested_room': "",
    'teacherreg_help_text_message_for_directors': "",
    'teacherreg_help_text_purchase_requests': "",
    'teacherreg_help_text_class_info': "",
    'teacherreg_label_duration': "",
    'teacherreg_label_class_size_max': "",
    'teacherreg_label_num_sections': "",
    'teacherreg_label_requested_room': "",
    'teacherreg_label_message_for_directors': "",
    'teacherreg_label_purchase_requests': "",
    'teacherreg_label_class_info': "",
    'display_registration_names': "",
}
